"""
Cerberus Dynamic Command Loader for Cowrie
This module allows Cowrie to read command outputs generated by the Cerberus morphing engine.
"""

from __future__ import annotations
import os
import json
from typing import Optional

# Path to Cerberus dynamic outputs (inside Cowrie container)
CERBERUS_DYNAMIC = "/data/cowrie-dynamic"

def load_cerberus_output(command_name: str, args: list = None) -> Optional[str]:
    """
    Load command output from Cerberus dynamic files.

    Args:
        command_name: Name of the command (e.g., 'docker', 'systemctl')
        args: Command arguments (for commands that have different outputs based on args)

    Returns:
        Command output as string, or None if not found
    """
    # Try bin/ first
    path = os.path.join(CERBERUS_DYNAMIC, "bin", command_name)
    if os.path.exists(path):
        try:
            with open(path, 'r') as f:
                return f.read()
        except Exception:
            pass

    # Try usr/bin/
    path = os.path.join(CERBERUS_DYNAMIC, "usr/bin", command_name)
    if os.path.exists(path):
        try:
            with open(path, 'r') as f:
                return f.read()
        except Exception:
            pass

    return None


def load_network_config() -> Optional[dict]:
    """
    Load Cerberus network configuration.

    Returns:
        Network config dict, or None if not found
    """
    config_path = os.path.join(CERBERUS_DYNAMIC, "network-config.json")
    if os.path.exists(config_path):
        try:
            with open(config_path, 'r') as f:
                return json.load(f)
        except Exception:
            pass
    return None


def load_behavior_config() -> Optional[dict]:
    """
    Load Cerberus behavioral adaptation config.

    Returns:
        Behavior config dict, or None if not found
    """
    config_path = os.path.join(CERBERUS_DYNAMIC, "behavior.conf")
    if os.path.exists(config_path):
        try:
            config = {}
            with open(config_path, 'r') as f:
                for line in f:
                    if '=' in line:
                        key, value = line.strip().split('=', 1)
                        config[key] = value
            return config
        except Exception:
            pass
    return None


def cerberus_available() -> bool:
    """Check if Cerberus dynamic directory exists."""
    return os.path.exists(CERBERUS_DYNAMIC)
