import os
import json
import logging
from typing import Dict, Any

# WHY THIS FIX: Synchronizing state between C-based Rubik's Cube engine and HoneyGPT
# ensures the LLM doesn't hallucinate files that "don't exist" in the honeypot's
# biological state.

class StateManager:
    def __init__(self, state_dir: str = "build/cowrie-dynamic"):
        self.state_dir = state_dir
        self.virtual_fs = {}
        self.load_state()

    def load_state(self):
        """Load state from Cerberus dynamic volumes."""
        # In a real deployment, we'd parse the actual honeyfs or shared JSON
        state_file = os.path.join(self.state_dir, "fs_state.json")
        if os.path.exists(state_file):
            try:
                with open(state_file, 'r') as f:
                    self.virtual_fs = json.load(f)
            except Exception as e:
                logging.error(f"Failed to load state: {e}")

    def get_context(self) -> str:
        """Generate a string representation of the current system state for the prompt."""
        context = "Current System State:\n"
        context += f"Filesystem: {len(self.virtual_fs)} dynamic entries tracked.\n"
        # Truncated for prompt efficiency
        context += "Key files: /etc/passwd, /etc/hostname, /proc/cpuinfo (morphed)\n"
        return context

    def update_state(self, changes: Dict[str, Any]):
        """Apply state changes generated by the LLM."""
        for path, content in changes.items():
            self.virtual_fs[path] = content

        # Sync back to shared volume if needed
        # self.save_state()
